spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        web-admin-password: beercontrol
        trace: false
      path: /database_config
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: none
        dialect: org.hibernate.dialect.H2Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy