server:
  port: 8080
  servlet:
    context-path: /beercontrol

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        web-admin-password: beercontrol
        trace: false
      path: /database_config
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.H2Dialect

application:
  description: Projeto desenvolvido no Bootcamp GFT Start ## 2Java
  version: 0.0.1-BIC
  msg_success: Moving was successfully carried out to the warehouse.

scheduling:
  notification_time: 10000
  movement_time: 10000
